### ISSUE TITLE
peer-generator creates nothing in Windows 10 with Qt 5.6.1

### ISSUE THREAD

**Issue by shaoxie1986** [HamedMasafi/Noron#2]
I follow the README.md, create a file named template.h, run "peer-generator.exe template.h",there's  no error ,but it create nothing.

My English is not good, hope you can understand.

**Comment by HamedMasafi** [comment]
Hi, Thanks for reporting.
Can I see your template?

**Comment by shaoxie1986** [comment]
class User : public NoronPeer {
    Q_PROPERTY(quint32 id)
    Q_PROPERTY(QString displayName)
    Q_PROPERTY(QImage avatar)

```
void sendMessage(QString message);
```

};

**Comment by shaoxie1986** [comment]
I open peer-generator.pro withe qtcreator, in debug mode, it shows "can't find linker symbol for virtual table for `QFile' value".
is there something wrong?

**Comment by shaoxie1986** [comment]
error is in main.cpp:line 70.
                .replace("pubic ", "");
it should be  .replace("public ", "");

**Comment by shaoxie1986** [comment]
and in line 83:
return EXIT_SUCCESS;
it always return.

**Comment by HamedMasafi** [comment]
You're right. This fail is because of I committed source sooner that stable milestone. 
This changes fixed in commit#20
