### ISSUE TITLE
there is no function named connectToHost in class NeuronPeer or User

### ISSUE THREAD

**Issue by jaafari** [HamedMasafi/Noron#4]
In code you provided as an example:
```
User *p = new User(this);
p->connectToHost("127.0.0.1", 8010);
p->sendMessage("Hello Neuron");
```

there is no function named connectToHost in class NeuronPeer or User

**Comment by HamedMasafi** [comment]
Hi Jaffari
__Neuron__ has many api changes during this years, For example connecting to server methods removed from __NeuronPeer__ and now __NeuronClientHub__ and __NeuronServerHub__ is responsible to c/s connection. I will try to make a new commit for examples folder based on new classes scheema. Be in touch.

BR
