### ISSUE TITLE
How is this library different from Qt Remote Objects module? 

### ISSUE THREAD

**Issue by rhvarrier** [HamedMasafi/Noron#8]
Hello,
Your library fulfills most of the needs of my current project. However, I have also found that Qt Remote Objects official module provides very similar functionality. How does your library differ from this one. Just curious to know more

**Comment by HamedMasafi** [comment]
Hi @Rhvarrier 
In point of technical view both have same job. Neuron was started as an internal project for our project before that QtRO was published. Both of them try to make an object(s) remotable  with a few differences:
Neuron did not add any precompile tool so everything works with codes and macros.
Neuron has an shared mechanism (plus to client <-> server mechanism) In this case an abject can be shared along all clients.
And may be there small differences too
